In [1]:
import pandas as pd

In [3]:
df1=pd.read_csv('/data/2012_2014_교통사망사고정보.csv',encoding='CP949')
df2=pd.read_csv('/data/도로교통공단_전국_사망교통사고정보(2015).csv',encoding='CP949')
df3=pd.read_csv('/data/도로교통공단_전국_사망교통사고(2016년).csv',encoding='CP949')
df4=pd.read_csv('/data/도로교통공단_전국_사망교통사고_2017.csv',encoding='CP949')
df5=pd.read_csv('/data/도로교통공단_전국_사망교통사고정보(2018).csv',encoding='CP949')
df6=pd.read_csv('/data/도로교통공단_사망교통사고정보(2019).csv',encoding='CP949')
df7=pd.read_csv('/data/도로교통공단_사망교통사고정보(2020).csv',encoding='CP949')
df8=pd.read_csv('/data/도로교통공단_사망 교통사고 정보_20211231.csv',encoding='CP949')
dfn=[df1, df2,df3, df4, df5, df6, df7, df8]

FileNotFoundError: [Errno 2] No such file or directory: '/data/2012_2014_교통사망사고정보.csv'

In [4]:
L=[]
for d in dfn:
    print(len(d.columns))
#     print(d.columns)
#     L.append(pd.DataFrame(d.columns))
#     print(L)
#     z=pd.concat(L,axis=1)

NameError: name 'dfn' is not defined

In [ ]:
발생년
발생년월일시분
주야
요일
사망자수
사상자수
중상자수
경상자수
부상신고자수
발생지시도
발생시군구
사고유형_대분류
사고유형_중분류
사고유형
(가해자) 법규위반
도로형태_대분류
도로형태
당사자_종별_1당_대분류(가해자_당사자종별)
당사자_종별_2당_대분류(피해자_당사자종별)
발생위치x
발생위치y
경도
위도

In [ ]:
df1

In [ ]:
df1.drop(['발생분','법규위반_대분류','당사자종별_1당','당사자종별_2당'],axis=1,inplace=True)
df1.columns

In [ ]:
df2.drop(['법규위반_대분류','가해자_당사자종별','피해자_당사자종별'],axis=1,inplace=True)
df2.columns

In [ ]:
df3.drop(['발생분','법규위반_대분류','당사자종별_1당','당사자종별_2당'],axis=1,inplace=True)
df3.columns

In [ ]:
df4.drop(['발생분','법규위반_대분류','당사자종별_1당','당사자종별_2당'],axis=1,inplace=True)

df4.columns

In [ ]:
df5.drop(['법규위반_대분류','가해자_당사자종별','피해자_당사자종별'],axis=1,inplace=True)
df5.columns

In [ ]:
df6.columns

In [ ]:
df7.columns

In [ ]:
df8.columns

In [ ]:
df8.columns=['발생년', '발생년월일시', '주야', '요일', '사망자수', '부상자수', '중상자수', '경상자수', '부상신고자수',
       '발생지시도', '발생지시군구', '사고유형_대분류', '사고유형_중분류', '사고유형', '가해자법규위반',
       '도로형태_대분류', '도로형태', '가해자_당사자종별', '피해자_당사자종별', '발생위치X(UTMK)',
       '발생위치Y(UTMK)', '경도', '위도']

In [ ]:
df=pd.concat(dfn)

In [ ]:
df.to_csv('2012-2021_교통사망사고정보.csv',encoding='CP949')

In [ ]:
df=pd.read_csv('2012-2021_교통사망사고정보.csv',encoding='CP949', index_col=0)

In [ ]:
df['발생지시_군']=df['발생지시도']+' '+df['발생지시군구']

In [ ]:
L=[]
for d in df['발생지시_군']:
    a=d.split(' ')[0]
    b=d.split(' ')[1]
    if '시' in a:
        L.append(a)
    elif '광주' == a:
        L.append(a)
    elif '대구' == a:
        L.append(a)
    elif '대전' == a:
        L.append(a)
    elif '부산' == a:
        L.append(a)
    elif '서울' == a:
        L.append(a)
    elif '세종' == a:
        L.append(a)
    elif '울산' == a:
        L.append(a)
    elif '인천' == a:
        L.append(a)
    else:
        L.append(b)

In [ ]:
L=pd.DataFrame(L)
M=L[0].unique()

In [ ]:
for m in M:
    print(m)

In [ ]:
df['발생지시_군']=L

In [ ]:
df.drop(['발생지시도', '발생지시군구'], axis=1,inplace=True)

In [ ]:
df.to_csv('2012_2021_교통사망사고정보.csv',encoding='CP949')

In [6]:
df=pd.read_csv('./data/2012_2021_교통사망사고정보.csv',encoding='CP949', index_col=0)

In [7]:
D=['광주','대구','대전','부산','서울','세종','울산','인천']
for i,d in enumerate(df['발생지시_군']):
    if d in D:
        df['발생지시_군'][i]=d+'시'

In [8]:
for i,d in enumerate(df['발생지시_군']):
    if '(통합)' in d :
        df['발생지시_군'][i]='창원시'

In [9]:
S=[]
for d in df['발생지시_군'].unique():
    S.append(d)

In [10]:
df.to_csv('2012_2021_교통사망사고정보.csv',encoding='CP949')

In [11]:
sum(df['발생지시_군'] =='세종시')

81

In [12]:
a='서울시, 인천시, 수원시, 강화군, 양평군, 이천시, 속초시, 강릉시, 태백시, 철원군, 평창군, 춘천시, 원주시, 인제군, 홍천군, 충주시, \
청주시, 영동군, 제천시, 보은군, 서산시, 대전시, 천안시, 보령시, 부여군, 금산군, 울진군, 안동시, 포항시, 대구시, 봉화군, 영주시, 문경시, \
영덕군, 의성군, 구미시, 영천시, 울산시, 창원시, 부산시, 통영시, 진주시, 거창군, 합천군, 밀양시, 산청군, 거제시, 남해군 , 군산시, 전주시, \
부안군, 임실군, 정읍시, 남원시, 장수군, 광주시, 목포시, 여수시, 완도군, 장흥군, 해남군, 고흥군, 제주시, 고산리, 성산구, 서귀포시'

In [13]:
Z=a.split(', ')

In [14]:
Q=[]
for s in S:
    if s not in Z:
        Q.append(s)

In [15]:
Q=pd.DataFrame(Q)

In [30]:
df1 = Q[50:]

In [39]:
df1['new'] = '수원시'

C:\Users\YONSAI\AppData\Local\Temp\ipykernel_10292\672661282.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['new'] = '수원시'

In [41]:
df1

       0  new  수원시
50   옥천군  수원시  화성시
51   군포시  수원시  NaN
52   서천군  수원시  NaN
53   아산시  수원시  NaN
54   경주시  수원시  NaN
55   오산시  수원시  NaN
56   신안군  수원시  NaN
57   장성군  수원시  NaN
58   나주시  수원시  NaN
59   군위군  수원시  NaN
60   무안군  수원시  NaN
61   횡성군  수원시  NaN
62   고양시  수원시  NaN
63   예산군  수원시  NaN
64  의정부시  수원시  NaN
65   담양군  수원시  NaN
66   파주시  수원시  NaN
67   영암군  수원시  NaN
68   김제시  수원시  NaN
69   부천시  수원시  NaN
70   공주시  수원시  NaN
71   양양군  수원시  NaN
72   양구군  수원시  NaN
73   화순군  수원시  NaN
74   홍성군  수원시  NaN
75   증평군  수원시  NaN
76   남해군  수원시  NaN
77   창녕군  수원시  NaN
78   하동군  수원시  NaN
79  동두천시  수원시  NaN
80   동해시  수원시  NaN
81   연천군  수원시  NaN
82   의령군  수원시  NaN
83   화천군  수원시  NaN
84   영월군  수원시  NaN
85   연기군  수원시  NaN
86   단양군  수원시  NaN
87   성주군  수원시  NaN
88   곡성군  수원시  NaN
89   과천시  수원시  NaN
90   청송군  수원시  NaN
91   삼척시  수원시  NaN
92   진도군  수원시  NaN
93   순창군  수원시  NaN
94   울릉군  수원시  NaN
95   영양군  수원시  NaN
96   계룡시  수원시  NaN
97   정선군  수원시  NaN
98   세종시  수원시  NaN
99   구례군  수원시  NaN

In [37]:
df1.loc[50, 'new'] = '화성시'

       0  new  수원시
50   옥천군  화성시  화성시
51   군포시  수원시  NaN
52   서천군  수원시  NaN
53   아산시  수원시  NaN
54   경주시  수원시  NaN
55   오산시  수원시  NaN
56   신안군  수원시  NaN
57   장성군  수원시  NaN
58   나주시  수원시  NaN
59   군위군  수원시  NaN
60   무안군  수원시  NaN
61   횡성군  수원시  NaN
62   고양시  수원시  NaN
63   예산군  수원시  NaN
64  의정부시  수원시  NaN
65   담양군  수원시  NaN
66   파주시  수원시  NaN
67   영암군  수원시  NaN
68   김제시  수원시  NaN
69   부천시  수원시  NaN
70   공주시  수원시  NaN
71   양양군  수원시  NaN
72   양구군  수원시  NaN
73   화순군  수원시  NaN
74   홍성군  수원시  NaN
75   증평군  수원시  NaN
76   남해군  수원시  NaN
77   창녕군  수원시  NaN
78   하동군  수원시  NaN
79  동두천시  수원시  NaN
80   동해시  수원시  NaN
81   연천군  수원시  NaN
82   의령군  수원시  NaN
83   화천군  수원시  NaN
84   영월군  수원시  NaN
85   연기군  수원시  NaN
86   단양군  수원시  NaN
87   성주군  수원시  NaN
88   곡성군  수원시  NaN
89   과천시  수원시  NaN
90   청송군  수원시  NaN
91   삼척시  수원시  NaN
92   진도군  수원시  NaN
93   순창군  수원시  NaN
94   울릉군  수원시  NaN
95   영양군  수원시  NaN
96   계룡시  수원시  NaN
97   정선군  수원시  NaN
98   세종시  수원시  NaN
99   구례군  수원시  NaN

In [ ]:
ggd = ['수원시', '고양시', '용인시', '성남시', '부천시', '화성시', '안산시', '남양주시', '안양시', '평택시', '시흥시', '파주시', '의정부시', '김포시', '광주시', '광명시', '군포시', '하남시', '오산시', '양주시', '이천시', '구리시', '안성시', '포천시', '의왕시', '양평군', '여주시', '동두천시', '가평군', '과천시', '연천군']

gwd = ['춘천시', '원주시', '강릉시', '동해시', '태백시', '속초시', '삼척시', '홍천군', '횡성군', '영월군', '평창군', '정선군', '철원군', '화천군', '양구군', '인제군', '고성군', '양양군']

cbd = ['청주시', '충주시', '제천시', '보은군', '옥천군', '영동군', '증평군', '진천군', '괴산군', '음성군', '단양군']

cnd = ['천안시', '공주시', '보령시', '아산시', '서산시', '논산시', '계룡시', '당진시', '금산군', '부여군', '서천군', '청양군', '홍성군', '예산군', '태안군']

jbd = ['전주시', '군산시', '익산시', '정읍시', '남원시', '김제시', '완주군', '진안군', '무주군', '장수군', '임실군', '순창군', '고창군', '부안군']

jnd = ['목포시', '여수시', '순천시', '나주시', '광양시', '담양군', '곡성군', '구례군', '고흥군', '보성군', '화순군', '장흥군', '강진군', '해남군', '영암군', '무안군', '함평군', '영광군', '장성군', '완도', '진도군', '신안군']

gbd = ['포항시', '경주시', '김천시', '안동시', '구미시', '영주시', '영천시', '상주시', '문경시', '경산시', '군위군', '의성군', '청송군', '영양군', '영덕군', '청도군', '고령군', '성주군', '칠곡군', '예천군', '봉화군', '울진군', '울릉군']

gnd = ['창원시', '진주시', '통영시', '사천시', '김해시', '밀양시', '거제시', '양산시', '의령군', '함안군', '창녕군', '고성군', '남해군', '하동군', '산청군', '함양군', '거창군', '합천군']

jjd = ['제주시', '서귀포시']

In [ ]:
gwd = ['춘천시', '원주시', '강릉시', '동해시', '태백시', '속초시', '삼척시', '홍천군', '횡성군', '영월군', '평창군', '정선군', '철원군', '화천군', '양구군', '인제군', '고성군', '양양군']

In [ ]:
cbd = ['청주시', '충주시', '제천시', '보은군', '옥천군', '영동군', '중평군', '진천군', '괴산군', '음성군', '단양군']

In [ ]:
cnd = ['천안시', '공주시', '보령시', '아산시', '서산시', '논산시', '계룡시', '당진시', '금산군', '부여군', '서천군', '청양군', '홍성군', '예산군', '태안군']

In [ ]:
jbd = ['전주시', '군산시', '익산시', '정읍시', '남원시', '김제시', '완주군', '진안군', '무주군', '장수군', '임실군', '순창군', '고창군', '부안군']

In [ ]:
jnd = ['목포시', '여수시', '순천시', '나주시', '광양시', '담양군', '곡성군', '구례군', '고흥군', '보서군', '화순군', '장흥군', '강진군', '해남군', '영암군', '무안군', '함평군', '영광군', '장성군', '완도', '진도군', '신안군']

In [ ]:
gbd = ['포항시', '경주시', '김천시', '안동시', '구미시', '영주시', '영천시', '상주시', '문경시', '경산시', '군위군', '의성군', '청송군', '영양군', '영덕군', '청도군', '고령군', '성주군', '칠곡군', '예천군', '봉화군', '울진군', '울릉군']

In [ ]:
gnd = ['창원시', '진주시', '통영시', '사천시', '김해시', '밀양시', '거제시', '양산시', '의령군', '함안군', '창녕군', '고성군', '남해군', '하동군', '산청군', '함양군', '거창군', '합천군']

In [ ]:
jjd = ['제주시', '서귀포시']

In [47]:
df1 = pd.read_csv('./data/날씨전체.csv', encoding = 'utf-8')

In [51]:
df = pd.read_csv('./날씨최종.csv')

In [54]:
df.drop('Unnamed: 0', axis =1, inplace = True)

In [55]:
df

,지점,지점명,일시,평균기온(°C),최저기온(°C),최고기온(°C),일강수량(mm),최대 풍속(m/s),평균 풍속(m/s),평균 이슬점온도(°C),최소 상대습도(%),평균 상대습도(%)
0,90,속초,2012-01-01,1.1,-1.5,4.9,0.0,5.7,2.2,-9.9,26.0,44.8
1,90,속초,2012-01-02,-0.3,-2.9,4.0,0.0,4.6,2.5,-9.3,39.0,50.9
2,90,속초,2012-01-03,-0.8,-4.2,3.7,0.0,8.3,2.8,-12.5,26.0,41.1
3,90,속초,2012-01-04,-2.6,-5.6,1.8,0.0,7.8,2.4,-16.0,23.0,35.4
4,90,속초,2012-01-05,-2.3,-5.8,2.8,0.0,5.1,2.5,-18.2,17.0,28.9
...,...,...,...,...,...,...,...,...,...,...,...,...
343888,295,남해,2021-12-27,-0.8,-8.0,3.9,0.0,5.0,1.7,-8.4,35.0,58.0
343889,295,남해,2021-12-28,3.3,-2.5,8.7,0.0,3.8,1.2,-3.1,45.0,64.4
343890,295,남해,2021-12-29,5.8,0.7,10.6,0.0,6.7,2.1,-1.8,43.0,59.8
343891,295,남해,2021-12-30,3.4,1.2,5.6,0.0,6.1,3.5,-6.8,29.0,48.1
343892,295,남해,2021-12-31,0.1,-3.5,3.9,0.0,5.3,2.6,-10.8,28.0,44.5